### ISSUE TITLE
Support swiftlint.path as workspace setting

### ISSUE THREAD

**Issue by robertherber** [vknabel/vscode-swiftlint#101]
I'm trying to set up SwiftLint for a folder structure where the iOS project is not in the root. Being able to set swiftlint.path on the workspace level would help a lot.

**Comment by vknabel** [comment]
Hi @robertherber, I understand the use case, but this might open up a vulnerability. If allowed any project could point `swiftlint.path` to a malicious binary.

Is Swiftlint added within the Package.swift manifest, which is too deeply nested? If so, how deep?

**Comment by robertherber** [comment]
@vknabel The issue is two-fold: 
- Since we're already using Cocoapods I prefer to not add an additional PM in this case (even though my experience with Swift PM has been good in other projects).
- This is for an open source library where it's installed in the /example directory.

**Comment by vknabel** [comment]
I see, didn't think about CocoaPods!
Already left a comment on your PR. After that it's ready to go.

Also feel free to bump the version to `1.8.5` in the same PR. That will be the version after the merge. ☺️
