### ISSUE TITLE
Report  Command failed: /usr/bin/swiftlint lint --quiet --reporter json --config /etc/default-swiftlint.ymlswiftlint: /home/build-user/swift/lib/IDE/SyntaxModel.cpp:1311: auto (anonymous namespace)::ModelASTWalker::handleAttrRanges(ArrayRef<(anonymous namespace)::ModelASTWalker::DeclAttributeAndRange>)::(anonymous class)::operator()(swift::SourceRange) const: Assertion `(TokenNodes.empty() || SM.isBeforeInBuffer(AttrRange.End, TokenNodes.front().Range.getStart())) 

### ISSUE THREAD

**Issue by rmecham** [vknabel/vscode-swiftlint#104]
`Error: Command failed: /usr/bin/swiftlint lint --quiet --reporter json --config /etc/default-swiftlint.yml
swiftlint: /home/build-user/swift/lib/IDE/SyntaxModel.cpp:1311: auto (anonymous namespace)::ModelASTWalker::handleAttrRanges(ArrayRef<(anonymous namespace)::ModelASTWalker::DeclAttributeAndRange>)::(anonymous class)::operator()(swift::SourceRange) const: Assertion `(TokenNodes.empty() || SM.isBeforeInBuffer(AttrRange.End, TokenNodes.front().Range.getStart())) && "AttrRange doesn't align with any TokenNode?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
os: linux`

**Comment by vknabel** [comment]
Thanks for the report, but this isn’t an issue of the extension. Try to replicate this crash on the command line and report it as issue to the llvm project.
