### ISSUE TITLE
.swiftlint.yml partially ignored?

### ISSUE THREAD

**Issue by fappelman** [vknabel/vscode-swiftlint#12]
I have the following .swiftlint.yml file:

```yaml
included:
  - Sources
```
If I run on the commandline, `swiftlint` will report a clean sheet, no issues.

If I then run this from `vscode` I get 7K errors.

The errors are in the top level directories `.macos` and `.linux`. Those are my build directories which are separated for `MacOS` and `Linux` builds. 

To add to this I added `excluded` lines to my config:

```yaml
included:
  - Sources
excluded:
  - .linux
  - .macos
```
This improves things but strange enough there are still 6 issues reported on files in the `.linux` and `.macos` directories. So apparently the configuration file `.swiftlint.yml` is seen and read but not fully followed up upon.

`vscode` itself creates an additional `.build` directory. That directory also contains the checked out code which is always ignored. So perhaps there is some hardcoding on the `.build` directory name here.

Finally if I run `swiftlint` from the terminal within `vscode` there are no issues.

I hope I have provided you with enough information here.

**Comment by vknabel** [comment]
@fappelman thanks for the report and the great description!

You are right: the following directories are hard-coded to be ignored. I thought it'd be a good default. Is it fine, or should I remove those?
https://github.com/vknabel/vscode-swiftlint/blob/d67f6f897cf6627a62dc2d0c183dbc8fe1546498/src/lint.ts#L113

I suppose you have opened few excluded files from `.linux` or `.macos`, right?
Currently this extension does not parse the config file. If you open a file, it will pass the contents directly to SwiftLint and it neither enforces `included` nor `excluded`.

I will have a look on parsing `.swiftlint.yml` configs. Though it might take more time than it initially seems, as vscode supports multiple workspace folders within one window and every single of those could have their own config.

**Comment by fappelman** [comment]
Thanks for coming back to me. If it is possible to actually read the `.swiftlint.yml` file that would be preferred. However if that is not possible than perhaps it would be an option to override the string `"**/{tmp,build,.build,Pods,Carthage}/**"` through a vscode configuration option. The current value could be the default.

**Comment by vknabel** [comment]
Released [1.2.0](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.2.0) which adds `swiftlint.forceExcludePaths` as you proposed.

Parsing the `.swiftlint.yml`-config is still planned.

**Comment by fappelman** [comment]
Thanks. Appreciated.

**Comment by fappelman** [comment]
Just want to let you know that since the update to `1.2.0` I get an error on startup:

```log
command 'semantic.refactor.command' already exists
```
The source is `Maintained Swift Development Environment` which is also from your hand.

**Comment by fappelman** [comment]
This is the stacktrace:

```log
Error: command 'semantic.refactor.command' already exists
	at _.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:547:974)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:792:899)
	at ExecuteCommandFeature.register (~/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:1501:53)
	at ExecuteCommandFeature.initialize (~/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:1491:14)
	at LanguageClient.initializeFeatures (~/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:2168:21)
	at ~/.vscode/extensions/unpublished.sourcekit-lsp-0.0.1/node_modules/vscode-languageclient/lib/client.js:1888:18
```

**Comment by vknabel** [comment]
It seems like `sourcekit-lsp` runs twice:
On the one hand by SDE and on the other hand by apples official extension. Try disabling one extension of both depending on your project.

**Comment by fappelman** [comment]
That seems to fix it. I will let you know if this cause other issues.

**Comment by vknabel** [comment]
@fappelman Good news: [1.2.1](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.2.1) will parse your SwiftLint config!

In case you have any trouble or experience an issue, feel free to text back!

**Comment by fappelman** [comment]
Great. Thanks.
