### ISSUE TITLE
SwiftLint reports issues for files that are in .git

### ISSUE THREAD

**Issue by fappelman** [vknabel/vscode-swiftlint#16]
I have run into the situation where `swiftlint` will warn me about issues that are about files that are in git and not in the active checked out code.

This issue can be recreated using the following steps:

1. Create some swift code.
1. Make certain there are a few `swiftlint` problems
1. Check in with the `swiftlint` problems
1. Fix the `swiftlint` problems so that `swiftlint` is silent
1. Check `source control` in the left hand side
1. Select the source that has been fixed but not check in yet
1. `VSCode` will open the file in comparison mode. One of them will show the *Working Tree*
1. At that moment `swiftlint` will start to report issues on the file that is currently in `git`

This is not a huge problem but it would be nice if `swiftlint` would ignore the *Working Tree*.

**Comment by fappelman** [comment]
One follow-up. After checking in the code where the issues have been fixed the "problems" are still listed.
Then by closing `vscode` and opening it again the issues are gone.

**Comment by vknabel** [comment]
Hi @fappelman! I haven't forgot you, but I didn't manage to have a look on this, yet.

**Comment by fappelman** [comment]
No worries. This is a workable bug.

**Comment by vknabel** [comment]
Hi @fappelman!
Just released the fix with the wonderful version of [1.2.3](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.2.3)!

**Comment by fappelman** [comment]
Thanks.
