### ISSUE TITLE
Report E2BIG spawn E2BIG

### ISSUE THREAD

**Issue by PetrPrazak** [vknabel/vscode-swiftlint#22]
```
Error: spawn E2BIG
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at spawn (child_process.js:549:9)
	at Object.execFile (child_process.js:233:17)
	at Object.module.<computed> [as execFile] (electron/js2c/asar.js:163:31)
	at /Users/prazak/.vscode/extensions/vknabel.vscode-swiftlint-1.2.4/out/lint.js:154:38
	at new Promise (<anonymous>)
	at execSwiftlint (/Users/prazak/.vscode/extensions/vknabel.vscode-swiftlint-1.2.4/out/lint.js:153:12)
	at Object.<anonymous> (/Users/prazak/.vscode/extensions/vknabel.vscode-swiftlint-1.2.4/out/lint.js:59:38)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/prazak/.vscode/extensions/vknabel.vscode-swiftlint-1.2.4/out/lint.js:5:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
os: darwin
```

_URL decoded contents by @vknabel_

**Comment by vknabel** [comment]
@PetrPrazak Thanks for the report!

Do you have any special setup?
Is the project where this error occurred open source, so I can reproduce the issue under the same circumstances?
Can you provide the path (or the length of it) to your repo?
Do you have any extension specific config? What does your swiftlint config look like?
Does it only happen in specific files? If yes: which one?

If you wonder regarding the weird questions: This might be related to long file paths and large projects.

**Comment by PetrPrazak** [comment]
Hi,
The project is unfortunately private.
The path is not really long: `/Users/prazak/dev/ring/ring-ios`
The problem happens right after installing the extension.
[the config file](https://gist.github.com/PetrPrazak/158b8f77a950bdc5b5ba5b19a0ca5e95)

**Comment by vknabel** [comment]
Thanks a lot @PetrPrazak.

Ist your project or file especially large?

**Comment by PetrPrazak** [comment]
The project is quite large (depending how you define large).
The files are of reasonable length.

**Comment by vknabel** [comment]
I just released an update. Unsure if it already fixes your issue, but could you have try?

**Comment by PetrPrazak** [comment]
Sure.
This time the error is different.
```
Error: Command failed: /usr/local/bin/swiftlint --quiet --reporter json --config /Users/prazak/dev/ring/ring-ios/.swiftlint.yml
Found a configuration for 'class_delegate_protocol' rule, but it is disabled on 'disabled_rules'.
No lintable files found at paths: ''

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)
os: darwin
```

**Comment by vknabel** [comment]
Thanks. What happens if you run the failing command yourself?

```bash
$ /usr/local/bin/swiftlint --quiet --reporter json --config /Users/prazak/dev/ring/ring-ios/.swiftlint.yml
```

**Comment by PetrPrazak** [comment]
That command prints the warning about the disabled rules and then it runs the scan on the whole tree and after a while it dumps the json with the warnings.
But if I add a parameter `--path` then it checks just that file:
```
$ /usr/local/bin/swiftlint --quiet --reporter json --config /Users/prazak/dev/ring/ring-ios/.swiftlint.yml --path ring/Dummy.swift
Found a configuration for 'class_delegate_protocol' rule, but it is disabled on 'disabled_rules'.
[

]
```
Or
```
$ /usr/local/bin/swiftlint --quiet --reporter json --config /Users/prazak/dev/ring/ring-ios/.swiftlint.yml --path ring/Ring/Entities/MoreInfoEntity.swift
Found a configuration for 'class_delegate_protocol' rule, but it is disabled on 'disabled_rules'.
[
  {
    "character" : 4,
    "file" : "\/Users\/prazak\/dev\/ring\/ring-ios\/ring\/Ring\/Entities\/MoreInfoEntity.swift",
    "line" : 48,
    "reason" : "TODOs should be resolved (xxx...).",
    "rule_id" : "todo",
    "severity" : "Warning",
    "type" : "Todo"
  },
  {
    "character" : 4,
    "file" : "\/Users\/prazak\/dev\/ring\/ring-ios\/ring\/Ring\/Entities\/MoreInfoEntity.swift",
    "line" : 66,
    "reason" : "TODOs should be resolved (xxx...).",
    "rule_id" : "todo",
    "severity" : "Warning",
    "type" : "Todo"
  }
]
```

**Comment by vknabel** [comment]
Thanks for the details. They really help a lot. 

If you wish, you can test wether the yet unreleased beta build [1.2.7-beta.0](https://github.com/vknabel/vscode-swiftlint/releases/tag/1.2.7-beta.0) works for you. Though it has not been tested enough to be released.

**Comment by PetrPrazak** [comment]
Seems to be working 👍 
One thought, though: You shouldn't by default run the swiftlint process on the whole tree, just on the opened file. The full scan should be available on demand.
Or is it possible to set it this way now?

**Comment by vknabel** [comment]
Great to hear!

Thanks for your suggestion. I created a new issue for it #25

**Comment by vknabel** [comment]
Good news: 1.2.7 is now officially released!
