### ISSUE TITLE
Force Exclude Paths ignored

### ISSUE THREAD

**Issue by JetA2** [vknabel/vscode-swiftlint#39]
Hi, thanks for the extension, very nice!

I'm having trouble with the "Force Exclude Paths" feature.
I've tested both relative (relative to what though?) and absolute paths, in user and workspace settings, nothing seems to make any difference.

Use case: in a Flutter project I want to exclude the "ios/Pods" directory.
I add the path "ios/Pods" to the exclude paths.

I know the settings file gets picked up since the "Enable" setting work, but linting happens in my excluded path anyway.
What could be the issue here?

**Comment by vknabel** [comment]
Hi @JetA2, thanks for the kind words and the report!

Yep, this seems to be a bug.
As a workaround, you can add the exclude to your .swiftlint config:

```yaml
excluded:
 - ios/Pods
```

Regarding your question: the `swiftlint.forceExcludePaths` paths are relative to the Workspace root of VS Code, not relative to your Swiftlint config.

**Comment by vknabel** [comment]
I decided to remove the `swiftlint.forceExcludePaths` config. You should use the `.swiftlint`-config instead.
