### ISSUE TITLE
Ability to lint on save

### ISSUE THREAD

**Issue by sasial-dev** [vknabel/vscode-swiftlint#40]
The ability to run `--fix` on save.

**Comment by vknabel** [comment]
@sasial-dev thanks for the suggestion!

Version [v1.5.0](https://github.com/vknabel/vscode-swiftlint/releases/tag/v1.5.0) implements this feature.

| Short Title               | Command                   |
| ------------------------- | ------------------------- |
| SwiftLint: Lint workspace | `swiftlint.lintWorkspace` |
| SwiftLint: Fix workspace  | `swiftlint.fixWorkspace`  |
| SwiftLint: Fix document   | `swiftlint.fixDocument`   |

To automatically fix all issues within a document on save, add the following to your `.vscode/settings.json`:

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
}
```
