### ISSUE TITLE
Could not find SwiftLint: /usr/local/bin/swiftlint

### ISSUE THREAD

**Issue by boenfu** [vknabel/vscode-swiftlint#42]
I expect to install lint like npm devDependencies only locally
But I got the title mistake.
It is fallback to global, and I see
```ts
   const possibleLocalPaths = [
          ".build/release/swiftlint",
          ".build/debug/swiftlint",
        ];
```
https://github.com/vknabel/vscode-swiftlint/blob/master/src/Current.ts#L101

But I just include these
![image](https://user-images.githubusercontent.com/33797740/165908968-280f2516-97db-46a3-95c3-7c210259d2b0.png)

Can you give me some help? thank you.

**Comment by vknabel** [comment]
Thanks for the feedback. This extension didn't build SwiftLint. Now it does: https://github.com/vknabel/vscode-swiftlint/releases/tag/1.7.0
