### ISSUE TITLE
Linux: The extension doesn't work if SwiftLint is used as a package

### ISSUE THREAD

**Issue by Zingam** [vknabel/vscode-swiftlint#44]
I have the same issue as with swift-format:

https://github.com/vknabel/vscode-apple-swift-format/issues/12#issuecomment-1159390602

Also if I have both packages added as a dependency then they fail to build but that's probably unrelated to the extension:

https://github.com/apple/swift-format/issues/377

**Comment by Zingam** [comment]
Running this from the Terminal got the extension to work:
> swift run -c release swiftlint --version

**Comment by vknabel** [comment]
See https://github.com/vknabel/vscode-apple-swift-format/issues/12#issuecomment-1159723595
