### ISSUE TITLE
Report  Command failed: /home/xxx/Desktop/SwiftTest/.build/release/swiftlint --quiet --reporter json --formatSourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

### ISSUE THREAD

**Issue by Zingam** [vknabel/vscode-swiftlint#45]
```
Error: Command failed: /home/xxx/Desktop/SwiftTest/.build/release/swiftlint --quiet --reporter json --format
SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
os: linux
```

**Comment by vknabel** [comment]
Hey @Zingam it seems like SwiftLint cannot find `libsourcekitdInProc.so`.

As taken from [realm/SwiftLint#working-with-multiple-swift-versions]( https://github.com/realm/SwiftLint#working-with-multiple-swift-versions):

>On Linux, SourceKit is expected to be located in `/usr/lib/libsourcekitdInProc.so` or specified by the `LINUX_SOURCEKIT_LIB_PATH` environment variable.

If your `libsourcekitdInProc.so` is not located at `/usr/lib/libsourcekitdInProc.so`, set `LINUX_SOURCEKIT_LIB_PATH` accordingly.
If you recently changed `LINUX_SOURCEKIT_LIB_PATH`, terminate VS Code and open it again from your terminal using `code .`. That way it should take the latest environment variable.
