### ISSUE TITLE
Report  Command failed: /opt/homebrew/bin/swiftlint --use-script-input-files --quiet --reporter json --formatSourceKittenFramework/File.swift:20: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogMsgTests.swift” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/akash/Documents/projects/SwiftUI/Jupiter/Tests/JupiterTests/LogMsgTests.swift, NSUnderlyingError=0x11ee0b0a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

### ISSUE THREAD

**Issue by akashgurava** [vknabel/vscode-swiftlint#46]
%60Error%3A%20Command%20failed%3A%20%2Fopt%2Fhomebrew%2Fbin%2Fswiftlint%20--use-script-input-files%20--quiet%20--reporter%20json%20--format%0ASourceKittenFramework%2FFile.swift%3A20%3A%20Fatal%20error%3A%20'try!'%20expression%20unexpectedly%20raised%20an%20error%3A%20Error%20Domain%3DNSCocoaErrorDomain%20Code%3D260%20%22The%20file%20%E2%80%9CLogMsgTests.swift%E2%80%9D%20couldn%E2%80%99t%20be%20opened%20because%20there%20is%20no%20such%20file.%22%20UserInfo%3D%7BNSFilePath%3D%2FUsers%2Fakash%2FDocuments%2Fprojects%2FSwiftUI%2FJupiter%2FTests%2FJupiterTests%2FLogMsgTests.swift%2C%20NSUnderlyingError%3D0x11ee0b0a0%20%7BError%20Domain%3DNSPOSIXErrorDomain%20Code%3D2%20%22No%20such%20file%20or%20directory%22%7D%7D%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A406%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A390%3A28)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1064%3A16)%0A%09at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A450%3A11)%0A%09at%20Socket.emit%20(node%3Aevents%3A390%3A28)%0A%09at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A687%3A12)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
Hi, thanks for the report. Did this error occurred once or repeatedly? Did you delete `/Users/akash/Documents/projects/SwiftUI/Jupiter/Tests/JupiterTests/LogMsgTests.swift` or a  folder containing it?
