### ISSUE TITLE
Report  Command failed: /opt/homebrew/bin/swiftlint --quiet --reporter json --formatxcrun: error: active developer path ("/Applications/Xcode-beta.app/Contents/Developer") does not existUse `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.See `man xcode-select` for more details.SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed

### ISSUE THREAD

**Issue by akashgurava** [vknabel/vscode-swiftlint#50]
%60Error%3A%20Command%20failed%3A%20%2Fopt%2Fhomebrew%2Fbin%2Fswiftlint%20--quiet%20--reporter%20json%20--format%0Axcrun%3A%20error%3A%20active%20developer%20path%20(%22%2FApplications%2FXcode-beta.app%2FContents%2FDeveloper%22)%20does%20not%20exist%0AUse%20%60sudo%20xcode-select%20--switch%20path%2Fto%2FXcode.app%60%20to%20specify%20the%20Xcode%20that%20you%20wish%20to%20use%20for%20command%20line%20developer%20tools%2C%20or%20use%20%60xcode-select%20--install%60%20to%20install%20the%20standalone%20command%20line%20developer%20tools.%0ASee%20%60man%20xcode-select%60%20for%20more%20details.%0ASourceKittenFramework%2Flibrary_wrapper.swift%3A31%3A%20Fatal%20error%3A%20Loading%20sourcekitd.framework%2FVersions%2FA%2Fsourcekitd%20failed%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A406%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A390%3A28)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1064%3A16)%0A%09at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A450%3A11)%0A%09at%20Socket.emit%20(node%3Aevents%3A390%3A28)%0A%09at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A687%3A12)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
Hi. Thanks for your report. It seems your currently selected Xcode toolchain refers to a beta version that you have no longer installed. 

A `sudo xcode-select --switch path/to/Xcode.app` should fix your issue.
