### ISSUE TITLE
Report  Command failed: /usr/local/bin/swiftlint --quiet --reporter json --formatSourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

### ISSUE THREAD

**Issue by DrEden33773** [vknabel/vscode-swiftlint#52]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Flocal%2Fbin%2Fswiftlint%20--quiet%20--reporter%20json%20--format%0ASourceKittenFramework%2Flibrary_wrapper.swift%3A31%3A%20Fatal%20error%3A%20Loading%20libsourcekitdInProc.so%20failed%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A399%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A526%3A28)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1092%3A16)%0A%09at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A451%3A11)%0A%09at%20Socket.emit%20(node%3Aevents%3A526%3A28)%0A%09at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A687%3A12)%0Aos%3A%20linux%60

**Comment by vknabel** [comment]
Hi, thanks for opening the issue. Sadly I wasn’t able to answer more quickly. I guess this was setup related, right?
