### ISSUE TITLE
Report 127 Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter json --formatenv: swiftlint: No such file or directory

### ISSUE THREAD

**Issue by Jchoque01** [vknabel/vscode-swiftlint#56]
```
Error: Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter json --format
env: swiftlint: No such file or directory

	at ChildProcess.exithandler (node:child_process:408:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
os: darwin
```

**Comment by vknabel** [comment]
Hi @Jchoque01, thanks for opening an issue!
Do have got swiftlint installed globally?
What happens if you run `which swiftlint` in your terminal?

**Comment by Jchoque01** [comment]
Hi vknabel. Yes, I already installed Swiftlint globally and running it from terminal, it works fine. However, when I try to run Vscode and open any file, it shows this error message

**Comment by vknabel** [comment]
That's weird.

Did you override the `swiftlint.path` config?
Does `which swiftlint` succeed?
Does `env swiftlint` succeed?

Did you start VS Code via the UI?
What if you completely quit VS Code and start it via terminal by running `code`?

I guess your VS Code has a different `$PATH` as your terminal.

**Comment by vknabel** [comment]
This error is setup related. SwiftLint needs to be installed into the PATH or the `swiftlint.path` needs to be set manually.
The error message has been improved here.
