### ISSUE TITLE
Report 127 Command failed: /usr/bin/env swiftlint lint --quiet --reporter json --format/usr/bin/env: ‘swiftlint’: No such file or directory

### ISSUE THREAD

**Issue by LACHKAR99ZAKARIA** [vknabel/vscode-swiftlint#57]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--quiet%20--reporter%20json%20--format%0A%2Fusr%2Fbin%2Fenv%3A%20%E2%80%98swiftlint%E2%80%99%3A%20No%20such%20file%20or%20directory%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A399%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A526%3A28)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1092%3A16)%0A%09at%20Process.ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A302%3A5)%0Aos%3A%20linux%60

**Comment by vknabel** [comment]
Hi @LACHKAR99ZAKARIA, have you installed `swiftlint`?
What happens if you run `which swiftlint`?

**Comment by vknabel** [comment]
This error is setup related. SwiftLint needs to be installed into the PATH or the `swiftlint.path` needs to be set manually.
The error message has been improved here.
