### ISSUE TITLE
Report  Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by swift-develop** [vknabel/vscode-swiftlint#62]
%60Error%3A%20Illegal%20argument%3A%20line%20must%20be%20non-negative%0A%20%20%20%20at%20S%20(%2FApplications%2FVisual%20Studio%20Code.app%2FContents%2FResources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fapi%2Fnode%2FextensionHostProcess.js%3A7%3A1267)%0A%20%20%20%20at%20new%20o%20(%2FApplications%2FVisual%20Studio%20Code.app%2FContents%2FResources%2Fapp%2Fout%2Fvs%2Fworkbench%2Fapi%2Fnode%2FextensionHostProcess.js%3A96%3A13329)%0A%20%20%20%20at%20%2FUsers%2Ftomgrant%2F.vscode%2Fextensions%2Fvknabel.vscode-swiftlint-1.8.3%2Fout%2Flint.js%3A197%3A31%0A%20%20%20%20at%20Array.map%20(%3Canonymous%3E)%0A%20%20%20%20at%20%2FUsers%2Ftomgrant%2F.vscode%2Fextensions%2Fvknabel.vscode-swiftlint-1.8.3%2Fout%2Flint.js%3A150%3A37%0A%20%20%20%20at%20Generator.next%20(%3Canonymous%3E)%0A%20%20%20%20at%20fulfilled%20(%2FUsers%2Ftomgrant%2F.vscode%2Fextensions%2Fvknabel.vscode-swiftlint-1.8.3%2Fout%2Flint.js%3A5%3A58)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
Closed in favor of #61

**Comment by swift-develop** [comment]
Sorry, however it does happen everytime I launch.
