### ISSUE TITLE
Report  Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonSourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

### ISSUE THREAD

**Issue by noexfield** [vknabel/vscode-swiftlint#63]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0ASourceKittenFramework%2Flibrary_wrapper.swift%3A31%3A%20Fatal%20error%3A%20Loading%20libsourcekitdInProc.so%20failed%0A%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A409%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Adomain%3A489%3A12)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1121%3A16)%0A%20%20%20%20at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A479%3A11)%0A%20%20%20%20at%20Socket.emit%20(node%3Aevents%3A513%3A28)%0A%20%20%20%20at%20Socket.emit%20(node%3Adomain%3A489%3A12)%0A%20%20%20%20at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A757%3A14)%0Aos%3A%20linux%60

**Comment by vknabel** [comment]
Hi @noexfield,
thanks for opening an issue. You need to have Xcode installed and re-compile/re-install swiftlint. Make sure, using swiftlint works from the command line.
