### ISSUE TITLE
レポートコマンドに失敗しました: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonSourceKittenFramework/File.swift:20: 致命的なエラー: 'try!'式は予期せずエラーを発生させた: Error Domain=NSCocoaErrorDomain Code=260 「そのようなファイルがないため、ファイル「DKAssetGroupDetailImageCell.swift」を開けませんでした。」UserInfo={NSFilePath=/Users/ir/Desktop/Sense0.0/sense_0/ios/Pods/DKImagePickerController/Sources/DKImagePickerController/View/Cell/DKAssetGroupDetailImageCell.swift, NSUnderlyingError=0x133f616b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}https://github.com/llvm/llvm-project/issues/にバグレポートを提出し、クラッシュバックトレースを含めてください。

### ISSUE THREAD

**Issue by brief69** [vknabel/vscode-swiftlint#65]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0ASourceKittenFramework%2FFile.swift%3A20%3A%20Fatal%20error%3A%20'try!'%20expression%20unexpectedly%20raised%20an%20error%3A%20Error%20Domain%3DNSCocoaErrorDomain%20Code%3D260%20%22The%20file%20%E2%80%9CDKAssetGroupDetailImageCell.swift%E2%80%9D%20couldn%E2%80%99t%20be%20opened%20because%20there%20is%20no%20such%20file.%22%20UserInfo%3D%7BNSFilePath%3D%2FUsers%2Fir%2FDesktop%2FSense0.0%2Fsense_0%2Fios%2FPods%2FDKImagePickerController%2FSources%2FDKImagePickerController%2FView%2FCell%2FDKAssetGroupDetailImageCell.swift%2C%20NSUnderlyingError%3D0x133f616b0%20%7BError%20Domain%3DNSPOSIXErrorDomain%20Code%3D2%20%22No%20such%20file%20or%20directory%22%7D%7D%0APLEASE%20submit%20a%20bug%20report%20to%20https%3A%2F%2Fgithub.com%2Fllvm%2Fllvm-project%2Fissues%2F%20and%20include%20the%20crash%20backtrace.%0A%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A408%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A526%3A28)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1092%3A16)%0A%20%20%20%20at%20Process.ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A302%3A5)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
Hi @brief69, thanks for your report. Though it seems like your issue happens on a lower level. Are you using the new Xcode beta?
