### ISSUE TITLE
Report  Command failed: /opt/homebrew/bin/swiftlint /usr/bin/env swiftlint lint --quiet --reporter jsonwarning: Configuration contains invalid keys identation.SourceKittenFramework/File.swift:20: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=261 "The file “env” couldn’t be opened using text encoding Unicode (UTF-8)." UserInfo={NSFilePath=/usr/bin/env, NSStringEncoding=4}PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

### ISSUE THREAD

**Issue by raphaeltorquat0** [vknabel/vscode-swiftlint#69]
%60Error%3A%20Command%20failed%3A%20%2Fopt%2Fhomebrew%2Fbin%2Fswiftlint%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--quiet%20--reporter%20json%0Awarning%3A%20Configuration%20contains%20invalid%20keys%20identation.%0ASourceKittenFramework%2FFile.swift%3A20%3A%20Fatal%20error%3A%20'try!'%20expression%20unexpectedly%20raised%20an%20error%3A%20Error%20Domain%3DNSCocoaErrorDomain%20Code%3D261%20%22The%20file%20%E2%80%9Cenv%E2%80%9D%20couldn%E2%80%99t%20be%20opened%20using%20text%20encoding%20Unicode%20(UTF-8).%22%20UserInfo%3D%7BNSFilePath%3D%2Fusr%2Fbin%2Fenv%2C%20NSStringEncoding%3D4%7D%0APLEASE%20submit%20a%20bug%20report%20to%20https%3A%2F%2Fgithub.com%2Fllvm%2Fllvm-project%2Fissues%2F%20and%20include%20the%20crash%20backtrace.%0A%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A409%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Adomain%3A489%3A12)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1121%3A16)%0A%20%20%20%20at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A479%3A11)%0A%20%20%20%20at%20Socket.emit%20(node%3Aevents%3A513%3A28)%0A%20%20%20%20at%20Socket.emit%20(node%3Adomain%3A489%3A12)%0A%20%20%20%20at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A757%3A14)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
Hi. Thanks for the report. It seems like your SwiftLint configuration was invalid.
