### ISSUE TITLE
Report  Command failed: /usr/bin/env swiftlint lint --quiet --reporter jsonSourceKittenFramework/File.swift:20: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “SerialExecutorTests.swift” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/MyUser/Development/Vapor/MyProject/.build/checkouts/swift-nio/Tests/NIOPosixTests/SerialExecutorTests.swift, NSUnderlyingError=0x13898b600 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

### ISSUE THREAD

**Issue by chibombo** [vknabel/vscode-swiftlint#70]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--quiet%20--reporter%20json%0ASourceKittenFramework%2FFile.swift%3A20%3A%20Fatal%20error%3A%20'try!'%20expression%20unexpectedly%20raised%20an%20error%3A%20Error%20Domain%3DNSCocoaErrorDomain%20Code%3D260%20%22The%20file%20%E2%80%9CSerialExecutorTests.swift%E2%80%9D%20couldn%E2%80%99t%20be%20opened%20because%20there%20is%20no%20such%20file.%22%20UserInfo%3D%7BNSFilePath%3D%2FUsers%2Fgenaro%2FDevelopment%2FVapor%2FMyProject%2F.build%2Fcheckouts%2Fswift-nio%2FTests%2FNIOPosixTests%2FSerialExecutorTests.swift%2C%20NSUnderlyingError%3D0x13898b600%20%7BError%20Domain%3DNSPOSIXErrorDomain%20Code%3D2%20%22No%20such%20file%20or%20directory%22%7D%7D%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A409%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%09at%20ChildProcess.emit%20(node%3Adomain%3A489%3A12)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1121%3A16)%0A%09at%20ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A304%3A5)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
The file to be listed has recently deleted. If this error repeats feel free to comment and reopen
