### ISSUE TITLE
Report  Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonwarning: Found a configuration for 'type_body_length' rule, but it is disabled on 'disabled_rules'.SourceKittenFramework/File.swift:20: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Color Extension.swift” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/user/Development/Git/app/Color Extension.swift, NSUnderlyingError=0x7ff5c571c650 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

### ISSUE THREAD

**Issue by chibombo** [vknabel/vscode-swiftlint#71]
When I'm doing code review using VS Code, Swiftlint is executed throwing this error.

I'm using this extension for code reviewing, I'm unsure if it is causing this behavior.

- [Extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)

%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0Awarning%3A%20Found%20a%20configuration%20for%20'type_body_length'%20rule%2C%20but%20it%20is%20disabled%20on%20'disabled_rules'.%0ASourceKittenFramework%2FFile.swift%3A20%3A%20Fatal%20error%3A%20'try!'%20expression%20unexpectedly%20raised%20an%20error%3A%20Error%20Domain%3DNSCocoaErrorDomain%20Code%3D260%20%22The%20file%20%E2%80%9CColor%2BExtension.swift%E2%80%9D%20couldn%E2%80%99t%20be%20opened%20because%20there%20is%20no%20such%20file.%22%20UserInfo%3D%7BNSFilePath%3D%2FUsers%2Fgenarovega%2FDevelopment%2FGit%2Faxschool_app_ios%2FRooms%2FHelpers%2FExtensions%2FColor%2BExtension.swift%2C%20NSUnderlyingError%3D0x7ff5c571c650%20%7BError%20Domain%3DNSPOSIXErrorDomain%20Code%3D2%20%22No%20such%20file%20or%20directory%22%7D%7D%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A431%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%09at%20ChildProcess.emit%20(node%3Adomain%3A489%3A12)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1091%3A16)%0A%09at%20ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A302%3A5)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
It seems you used `type_body_length` although it was disabled in `disabled_rules`.
