### ISSUE TITLE
Report 1 Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonError: No lintable files found at paths: ''

### ISSUE THREAD

**Issue by xilopaint** [vknabel/vscode-swiftlint#78]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0AError%3A%20No%20lintable%20files%20found%20at%20paths%3A%20''%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A409%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%09at%20ChildProcess.emit%20(node%3Adomain%3A489%3A12)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1093%3A16)%0A%09at%20ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A302%3A5)%0Aos%3A%20darwin%60

**Comment by xilopaint** [comment]
I'm getting this on the Cursor editor.

**Comment by xilopaint** [comment]
This is getting triggered by the chat of the Cursor editor.

**Comment by xilopaint** [comment]
This error has been consistently triggered by the AI chat of the Cursor editor.

**Comment by vknabel** [comment]
Should be fixed with #85 and #90
