### ISSUE TITLE
Report  Command failed: /home//SDKs/Swift/swift-tools/SwiftLint/.build/release/swiftlint lint --quiet --reporter jsonSourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

### ISSUE THREAD

**Issue by H-G-Hristov** [vknabel/vscode-swiftlint#84]
%60Error%3A%20Command%20failed%3A%20%2Fhome%2Fhristo%2FSDKs%2FSwift%2Fswift-tools%2FSwiftLint%2F.build%2Frelease%2Fswiftlint%20lint%20--quiet%20--reporter%20json%0ASourceKittenFramework%2Flibrary_wrapper.swift%3A31%3A%20Fatal%20error%3A%20Loading%20libsourcekitdInProc.so%20failed%0A%0A%09at%20ChildProcess.exithandler%20(node%3Achild_process%3A431%3A12)%0A%09at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%09at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1091%3A16)%0A%09at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A449%3A11)%0A%09at%20Socket.emit%20(node%3Aevents%3A513%3A28)%0A%09at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A322%3A12)%0Aos%3A%20linux%60

**Comment by vknabel** [comment]
Should be fixed with #85 and #90
