### ISSUE TITLE
Report  Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonSourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed

### ISSUE THREAD

**Issue by jkaunert** [vknabel/vscode-swiftlint#96]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0ASourceKittenFramework%2Flibrary_wrapper.swift%3A58%3A%20Fatal%20error%3A%20Loading%20sourcekitdInProc.framework%2FVersions%2FA%2FsourcekitdInProc%20failed%0A%0A%20%20%20%20at%20genericNodeError%20(node%3Ainternal%2Ferrors%3A984%3A15)%0A%20%20%20%20at%20wrappedFn%20(node%3Ainternal%2Ferrors%3A538%3A14)%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A423%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A519%3A28)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Adomain%3A488%3A12)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1105%3A16)%0A%20%20%20%20at%20Process.ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A305%3A5)%0A%20%20%20%20at%20Process.callbackTrampoline%20(node%3Ainternal%2Fasync_hooks%3A130%3A17)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
This seems to be an issue while running swiftlint itself. Make sure to be able to run it directly.
