### ISSUE TITLE
Report 1 Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonwarning: Invalid configuration for 'indentation' rule. Falling back to default.Error: No lintable files found at paths: ''

### ISSUE THREAD

**Issue by zmz20240701** [vknabel/vscode-swiftlint#98]
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0Awarning%3A%20Invalid%20configuration%20for%20'indentation'%20rule.%20Falling%20back%20to%20default.%0AError%3A%20No%20lintable%20files%20found%20at%20paths%3A%20''%0A%0A%20%20%20%20at%20genericNodeError%20(node%3Ainternal%2Ferrors%3A984%3A15)%0A%20%20%20%20at%20wrappedFn%20(node%3Ainternal%2Ferrors%3A538%3A14)%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A423%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A519%3A28)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1105%3A16)%0A%20%20%20%20at%20Process.ChildProcess._handle.onexit%20(node%3Ainternal%2Fchild_process%3A305%3A5)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment]
Hey @zmz20240701, it seems like your swiftlint config is invalid. Especially the `indentation` rule. Make sure your config is valid and that swiftlint succeeds at the command line.
